const SNIPPET_LOADED = 'SNIPPET_LOADED'
const SET_SNIPPET_LANGUAGE = 'SET_SNIPPET_LANGUAGE'
const CHANGE_SNIPPET_LANGUAGE = 'CHANGE_SNIPPET_LANGUAGE'

export {
  SNIPPET_LOADED,
  SET_SNIPPET_LANGUAGE,
  CHANGE_SNIPPET_LANGUAGE
}
